/**
 * KlausurenService
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface KlausurRequest { 
    semester: number;
    studiengang: string;
    jahr: string;
    modul: string;
    prof?: string;
    fileArray: Blob;
    uploadedFrom: string;
}